apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1                # ← K8S_DEPLOYMENT_NAME en GitHub Secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
        - name: backend1-app    # ← K8S_CONTAINER_NAME en GitHub Secrets
          image: nginx:alpine   # placeholder, el workflow lo reemplaza con kubectl set image
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: DB_ENDPOINT
              value: backend1-mysql-service   # nombre del Service de MySQL (abajo)
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend1-db-secret
                  key: MYSQL_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend1-db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend1-db-secret
                  key: MYSQL_PASSWORD
