apiVersion: v1
kind: Service
metadata:
  name: backend1-service
spec:
  selector:
    app: backend1
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP   # solo accesible dentro del cluster (frontend le habla por este nombre)
